flowchart TD
  main --> le_loop
  le_loop -->|"se '\n'"| incrementa_linha
  le_loop --> verifica_ultima_linha
  verifica_ultima_linha --> fim_arq
  fim_arq --> le_nums
  le_nums --> ler_linha
  ler_linha --> str_para_float
  str_para_float --> chamar_ordena
  chamar_ordena --> ordena
  ordena -->|"tipo_ord = 2"| usa_quick_sort
  usa_quick_sort --> ordena_quick
  ordena_quick -->|"a1 >= a2"| fim_quick
  ordena_quick --> particiona
  particiona --> loop_particiona
  loop_particiona --> fim_particiona
  fim_particiona --> ordena_quick_1["ordena_quick (esq, p-1)"]
  ordena_quick_1 --> ordena_quick_2["ordena_quick (p+1, dir)"]
  ordena_quick_2 --> fim_quick
  fim_quick --> fim_ordena
  fim_ordena --> imprimir
  imprimir --> printa_loop
  printa_loop --> float_para_str
  float_para_str --> fim_printa